CREATE TABLE user_service.chat_membership_intervals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES user_service.chat_rooms(room_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    start_seq BIGINT NOT NULL,
    end_seq BIGINT,
    CHECK (end_seq IS NULL OR end_seq >= start_seq)
);
CREATE INDEX idx_chat_membership_visible ON user_service.chat_membership_intervals(room_id,user_id,start_seq,end_seq);
CREATE UNIQUE INDEX uq_chat_membership_open ON user_service.chat_membership_intervals(room_id,user_id) WHERE end_seq IS NULL;
-- Past join/leave windows cannot be reconstructed from joined_at and read pointers.
-- Deploy only to an empty membership table, or prepare an independently reviewed exact mapping.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM user_service.chat_participants) THEN
        RAISE EXCEPTION 'V021 requires reviewed historical membership interval mapping; existing participants found';
    END IF;
END $$;
